### PR TITLE
Fix NuGet API calls in install script

### PR DESCRIPTION
**Pull request by davidxuang**
Changes per title.

### CODE REVIEW

**Comment by JoonghyunCho** [comment]
Hello, I don't see the reason the package ID has to be the lower case. Any reason for this change?

**Comment by davidxuang** [comment]
It's failing.

图片

**Comment by davidxuang** [comment]
Is this being reviewed? This does not affect development much because it can be bypassed if you name a version explicitly when executing the script, but it's not practical to do this with CI every time .NET receive a new minor series.

**Comment by JoonghyunCho** [comment]
sorry for the late review.
I still don't see the reason this should be changed. To me, it looks just an additional job in the script.
Additionally, as far as I know, the NOT ToLower() version is the exact url. 
I don't understand the original url fails on your side.

**Comment by davidxuang** [comment]
> sorry for the late review. I still don't see the reason this should be changed. To me, it looks just an additional job in the script. Additionally, as far as I know, the NOT ToLower() version is the exact url. I don't understand the original url fails on your side.

For no way the current implementation is working.

图片

**Comment by JoonghyunCho** [comment]
Ok, so you mean it could be failing in some CI or other system that probably handle it differently.
I will merge it and see if this could solve the issue. Thanks for the contribution.

**Review by JoonghyunCho — APPROVED** [review]
thanks

**Pull request merged**
